// Code generated by sqlc. DO NOT EDIT.
// source: cleanup.sql

package db

import (
	"context"
)

const cleanUpDB = `-- name: CleanUpDB :exec
TRUNCATE accounts, users RESTART IDENTITY CASCADE
`

func (q *Queries) CleanUpDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanUpDB)
	return err
}
