apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 602441236330.dkr.ecr.eu-central-1.amazonaws.com/simplebank:dff74b81ae4b7b9c694c9ece377937a66a611abf
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: simple-bank-secret