apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-bank-api-service
  name: simple-bank-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-bank-api
